# Generated by Django 6.0.7 on 2026-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 1 Hour Unlimited, Daily 1GB', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Target payment amount', max_digits=10)),
                ('radiusdesk_profile_id', models.IntegerField(help_text='Target Profile ID in RADIUSdesk')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 for unlimited')),
                ('data_limit_mb', models.PositiveIntegerField(default=0, help_text='0 for unlimited')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(max_length=20)),
                ('raw_text', models.TextField()),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('INVALID', 'Invalid/Ignored')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('radiusdesk_username', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
