# Generated by Django 6.0.7 on 2026-08-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotplan',
            name='radiusdesk_cloud_id',
            field=models.IntegerField(default=23, help_text='The Cloud ID in RADIUSdesk (e.g., 23)'),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='radiusdesk_owner_id',
            field=models.IntegerField(default=31, help_text='The Owner / User ID in RADIUSdesk (default 31 for root)'),
        ),
        migrations.AddField(
            model_name='hotspotplan',
            name='radiusdesk_realm_id',
            field=models.IntegerField(default=19, help_text='The Realm ID in RADIUSdesk (e.g., 19)'),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Target payment amount in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotspotplan',
            name='radiusdesk_profile_id',
            field=models.IntegerField(help_text='The Profile ID in RADIUSdesk (e.g., 46)'),
        ),
    ]
