# Generated by Django 6.0.7 on 2026-08-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_gateway', '0002_hotspotplan_radiusdesk_cloud_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_sender_ids', models.TextField(blank=True, default='', help_text='Comma-separated sender IDs allowed to trigger processing, e.g. 256700000000,256700000001')),
                ('admin_allowed_ips', models.TextField(blank=True, default='127.0.0.1, ::1', help_text='Comma-separated IP addresses allowed to access the admin panel')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
