# Generated by Django 6.0.7 on 2026-08-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_gateway', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='amount_regex',
            field=models.CharField(default='(?:UGX|KES|Ksh|Amt:)\\s*([\\d,]+)', help_text='Regex used to extract the payment amount from an incoming SMS.', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='transaction_ref_regex',
            field=models.CharField(default='(?:Txn ID|Transaction ID):\\s*([A-Z0-9]+)', help_text='Regex used to extract the transaction reference from an incoming SMS.', max_length=255),
        ),
    ]
